- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
  - maven
  - mysql

- name: install PYMYSQL and cryptography
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PYMYSQL
  - cryptography 


  - name: install maven dependecies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: "mv target/{{ component }}-1.0.jar {{ component }}.jar"
    args:
      chdir: /app
